#!/bin/bash
# install on Ubuntu 15.10 64-bit server using: 
# wget https://raw.githubusercontent.com/smeggie/scripts/master/teamspeakstuff ; chmod 744 teamspeakstuff ; ./teamspeakstuff ; sleep 2 ; cat /var/log/syslog | grep token
# See resource usage:
# ps -C ts3server_linux -o %cpu,%mem,cmd
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
wget http://dl.4players.de/ts/releases/3.5.0/teamspeak3-server_linux_amd64-3.5.0.tar.bz2
adduser --disabled-password --gecos "" teamspeak3
tar xvjf teamspeak3-server_linux_amd64-3.5.0.tar.bz2
mv teamspeak3-server_linux-amd64 /usr/local/teamspeak3
chown -R teamspeak3 /usr/local/teamspeak3
echo "#!/bin/sh" > /etc/init.d/teamspeak3
echo 'su -c "/usr/local/teamspeak3/ts3server_startscript.sh $@" teamspeak3' >> /etc/init.d/teamspeak3
sudo chmod u+x /etc/init.d/teamspeak3
sudo update-rc.d teamspeak3 defaults
sudo service teamspeak3 start
ufw allow 9987/udp
yes | ufw enable
ufw status
cat /var/log/syslog | grep login
echo "Getting token from: /var/log/syslog"

# get new priv key
# telnet 127.0.0.1 10011
# login serveradmin adminpw
# use 1
# tokenadd tokentype=0 tokenid1=6 tokenid2=0
